name: Pipeline DEV

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - test
      - main

jobs:
  validar-projeto:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Instalar dependências
        run: npm ci
      - name: Validar boas práticas no código
        run: npm run lint
      - name: Rodar testes automatizados
        run: npm test
      - name: Compilar frontend
        run: npm run build
